### ISSUE TITLE
Static hosting

### ISSUE THREAD

**Issue by xamgore** [AlexandraOlegovna/AlexandraOlegovna.github.io#1]
It's great you have made this repository public! 👍 

But it will be even better, if you upload all pages to some static hosting, for example [github pages](https://pages.github.com/) or [google cloud](https://cloud.google.com/). Give it a try! :wink:

**Comment by AlexandraOlegovna** [comment]
https://alexandraolegovna.github.io/Lesson1/dist/

**Comment by xamgore** [comment]
Cool! In the future try using `close #1` inside of commit messages to force github to close the issue.
